### ISSUE TITLE
Don't work Build Logs

### ISSUE THREAD

**Issue by Martin25699** [CrazyGamesCom/unity-optimizations-package#12]
Error:
<img width="912" alt="Снимок экрана 2023-09-14 в 11 20 55" src="https://github.com/CrazyGamesCom/unity-optimizations-package/assets/10417137/3c49cc0c-9300-495c-850b-9297bc2142d3">

OS: MacOS Ventura 13.5.2

Unity: 2022.3.5f1

**Comment by florin-cg** [comment]
Hi @Martin25699, did you get this error with the code from the repo, or the one from CrazySDK? We recently merged a PR here that fixes build log parsing on Mac, but don't yet have the latest code in CrazySDK.

**Comment by Martin25699** [comment]
from repo, I think need make a “clean build”, I’ll check it and report back, thanks for the quick response
